name: Update age

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 19 1 *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update age
        run: |
          NEW_AGE="$((`date +'%Y'` - 2006))",
          sed "s/<+AGE+>/$NEW_AGE/" ./README_Template.md > ./README.md

      - name: Commit and push changes
            run: |
              git config --global user.email "${{ secrets.EMAIL }}"
              git config --global user.name "${{ secrets.NAME }}"
              git add .
              git commit -m "Automatic updatet age"
              git push origin main
